"""empty message

Revision ID: 742f48fe3be2
Revises: 3e61e1a1249d
Create Date: 2021-11-05 10:15:53.785362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742f48fe3be2'
down_revision = '3e61e1a1249d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
